name: Sync Docker Images to Alibaba Cloud from Docker Compose

on:
  push:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from current repository
      uses: actions/checkout@v3
      with:
        path: current-repo

    - name: List files in the current repository
      run: |
        echo "Listing files in the current repository"
        ls -alh current-repo

    - name: Read version from dify-version.txt in current repository
      id: read_version
      run: |
        version=$(cat current-repo/dify-version.txt)
        echo "Dify version: $version"
        echo "version=$version" >> $GITHUB_ENV

    - name: Checkout code from Dify repo
      uses: actions/checkout@v3
      with:
        repository: langgenius/dify
        path: dify-repo

    - name: Checkout specific tag from Dify repo
      run: |
        echo "Checking out version tag: ${{ env.version }}"
        cd dify-repo
        git fetch --tags
        git checkout "tags/${{ env.version }}"

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.27.3/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Parse docker-compose.yaml for images
      id: parse_docker_compose
      run: |
        images=$(yq e '.services[].image // ""' dify-repo/docker/docker-compose.yaml | grep -v '^$' | tr '\n' ' ')
        echo "Images: $images"
        echo "images=$images" >> $GITHUB_ENV

    - name: Log in to Alibaba Cloud ACR
      run: |
        echo "Logging into Alibaba Cloud ACR"
        echo "${{ secrets.ACR_PASSWORD }}" | docker login crpi-myiq3tviozpbqdlj.cn-hangzhou.personal.cr.aliyuncs.com --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Pull and push images to Alibaba Cloud ACR
      run: |
        for image in ${{ env.images }}; do
          echo "Processing image: $image"
          docker pull $image
          image_tag=$(echo $image | awk -F'/' '{print $NF}')
          acr_image="crpi-myiq3tviozpbqdlj.cn-hangzhou.personal.cr.aliyuncs.com/lhaoyu/$image_tag"
          echo "Tagging image: $acr_image"
          docker tag $image $acr_image
          docker push $acr_image
          docker rmi $image $acr_image
        done
